graph TD
    A(Início) --> B[Leitura do DynamoDB]
    B --> C[Dividir CCIs em lotes de 100]
    C --> D{Iterar sobre os Lotes}
    
    %% Trabalho Paralelo começa aqui
    subgraph Processamento de Lotes em Paralelo
    D --> |Lote 1| E1[Chamar API de Mapeamento id_eq3 para Lote 1]
    D --> |Lote 2| E2[Chamar API de Mapeamento id_eq3 para Lote 2]
    D --> |Lote N| EN[Chamar API de Mapeamento id_eq3 para Lote N]
    
    E1 --> F1{Sucesso?}
    F1 --> |Sim| G1[Adicionar Resultado do Lote 1 ao Agrupamento]
    F1 --> |Não| H1[Retentar Chamada API Lote 1]
    H1 --> I1{Sucesso após Retentativa?}
    I1 --> |Sim| G1
    I1 --> |Não| J1[Registrar Erro Lote 1 no CloudWatch]

    E2 --> F2{Sucesso?}
    F2 --> |Sim| G2[Adicionar Resultado do Lote 2 ao Agrupamento]
    F2 --> |Não| H2[Retentar Chamada API Lote 2]
    H2 --> I2{Sucesso após Retentativa?}
    I2 --> |Sim| G2
    I2 --> |Não| J2[Registrar Erro Lote 2 no CloudWatch]

    EN --> FN{Sucesso?}
    FN --> |Sim| GN[Adicionar Resultado do Lote N ao Agrupamento]
    FN --> |Não| HN[Retentar Chamada API Lote N]
    HN --> IN{Sucesso após Retentativa?}
    IN --> |Sim| GN
    IN --> |Não| JN[Registrar Erro Lote N no CloudWatch]
    end
    %% Trabalho Paralelo termina aqui

    G1 --> K[Agrupar Resultados de Todos os Lotes]
    G2 --> K
    GN --> K
    K --> L[Publicar Agrupamento no SNS]
    L --> M(Fim)
